#Script for including all the other functions

  include("getalpha.jl")
  include("numerovfunc.jl")
  include("GetAtomParams.jl")
  include("Rb87numbers.jl")
  include("filenamemake.jl")
  include("SIunits.jl")
  include("krondelt.jl")
  include("triangle_coeff.jl")
  include("Wigner6j.jl")
  include("Wigner6jcheck.jl")
  include("fung.jl")
  include("tfunction3j.jl")
  include("Wigner3j.jl")
  include("ClebschGord.jl")
  include("radiel.jl")
  include("matrix_elements.jl")
  include("Radiative_lifetimes.jl")
  include("Rb87DecayPaths.jl")
  include("Rb87blackbody.jl")
  include("firstexcitedrabiRb.jl")
  include("matrixel2p.jl")
  include("angcalc.jl")
  include("BlockadeShift.jl")
  include("rectpulse.jl")
  include("combvechack.jl")
  include("envalfunc.jl")
